language: node_js
node_js:
  - "11"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

before_deploy: "echo 'Deploying'"

deploy:
  provider: npm
  email: "yaroschiffelers@gmail.com"
  api_key: "AUTH_TOKEN"
  on:
    tags: true
    branch: master

after_deploy: "echo 'Deployed succesful'"
